name: On PR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: tagshelfsrl/action-semantic-pull-request@main
        with:
          types: |
            chore
            docs
            fix
            feat
            misc
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout alfred-node
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

  release:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: tagshelfsrl/github-actions/.github/workflows/semver.yml@v1.12.0
    secrets:
      token: ${{ secrets.PAT_TOKEN }}
